# Importing the Necessary Libraries

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

# Reading the Datasets

In [2]:
blr_lst = pd.read_csv("../Data/Gap Filled LST/LST_Daily_BLR_GF.csv")
hyd_lst = pd.read_csv("../Data/Gap Filled LST/LST_Daily_HYD_GF.csv")  
pune_lst = pd.read_csv("../Data/Gap Filled LST/LST_Daily_Pune_GF.csv")

In [3]:
# Daily Dew Point Temperatures
blr_dpt = pd.read_csv("../Data/Dew Point Temperature/DPT_BLR.csv")
hyd_dpt = pd.read_csv("../Data/Dew Point Temperature/DPT_HYD.csv")
pune_dpt = pd.read_csv("../Data/Dew Point Temperature/DPT_Pune.csv")

In [4]:
# Daily Atomospheric Pressure
blr_ap = pd.read_csv("../Data/Atmospheric Pressure/AP_BLR.csv")
hyd_ap = pd.read_csv("../Data/Atmospheric Pressure/AP_HYD.csv")
pune_ap = pd.read_csv("../Data/Atmospheric Pressure/AP_Pune.csv")

In [5]:
# Wind Components
blr_wind = pd.read_csv("../Data/Wind Components/WindComponents_BLR.csv")
hyd_wind = pd.read_csv("../Data/Wind Components/WindComponents_HYD.csv")
pune_wind = pd.read_csv("../Data/Wind Components/WindComponents_Pune.csv")

In [6]:
# Air Temperatures
blr_at = pd.read_csv("../Data/Air Temperature/AT_BLR.csv")
hyd_at = pd.read_csv("../Data/Air Temperature/AT_HYD.csv")
pune_at = pd.read_csv("../Data/Air Temperature/AT_PUNE.csv")

In [7]:
# Loading the Albedo_BSA_shortwave. 
# Inversely proportional to LST.
# Captures the total reflected solar radiation.
blr_albedo = pd.read_csv("../Data/Albedo/Albedo_BSA_shortwave_BLR_New.csv")
hyd_albedo = pd.read_csv("../Data/Albedo/Albedo_BSA_shortwave_HYD_New.csv")
pune_albedo = pd.read_csv("../Data/Albedo/Albedo_BSA_shortwave_Pune_New.csv")

In [8]:
# Loading the evaporation_from_bare_soil_sum
# The amount of evaporation from bare soil at the top of the land surface. 
# This variable is accumulated from the beginning of the forecast time to the end of the forecast step.
# Unit is m of water equivalent
blr_evap_soil = pd.read_csv("../Data/Evaporation From Bare Soil/evaporation_from_bare_soil_sum_BLR_New.csv")
hyd_evap_soil = pd.read_csv("../Data/Evaporation From Bare Soil/evaporation_from_bare_soil_sum_HYD_New.csv")
pune_evap_soil = pd.read_csv("../Data/Evaporation From Bare Soil/evaporation_from_bare_soil_sum_Pune_New.csv")

In [9]:
# Loading evaporation_from_vegetation_transpiration_sum
# Amount of evaporation from vegetation transpiration. This has the same meaning as root extraction i.e. the amount of water extracted from the different soil layers. 
# This variable is accumulated from the beginning of the forecast time to the end of the forecast step.
# m of water equivalent
blr_evap_veg = pd.read_csv("../Data/Evaporation From Vegetation Transpiration/evaporation_from_vegetation_transpiration_sum_BLR_New.csv")
hyd_evap_veg = pd.read_csv("../Data/Evaporation From Vegetation Transpiration/evaporation_from_vegetation_transpiration_sum_HYD_New.csv")
pune_evap_veg = pd.read_csv("../Data/Evaporation From Vegetation Transpiration/evaporation_from_vegetation_transpiration_sum_Pune_New.csv")

In [10]:
# NDVI
blr_ndvi = pd.read_csv("../Data/NDVI/NDVI_BLR_New.csv")
hyd_ndvi = pd.read_csv("../Data/NDVI/NDVI_HYD_New.csv")
pune_ndvi = pd.read_csv("../Data/NDVI/NDVI_Pune_New.csv")

In [11]:
# precipitation 
# Unit is mm/d
blr_precip = pd.read_csv("../Data/Precipitation/precipitation_BLR_New.csv")
hyd_precip = pd.read_csv("../Data/Precipitation/precipitation_HYD_New.csv")
pune_precip = pd.read_csv("../Data/Precipitation/precipitation_Pune_New.csv")

In [12]:
# Surface Net Solar Radiation
# Unit is J/m^2
blr_solar = pd.read_csv("../Data/Surface Net Solar Radiation/surface_net_solar_radiation_sum_BLR_New.csv")
hyd_solar = pd.read_csv("../Data/Surface Net Solar Radiation/surface_net_solar_radiation_sum_HYD_New.csv")
pune_solar = pd.read_csv("../Data/Surface Net Solar Radiation/surface_net_solar_radiation_sum_Pune_New.csv")

In [13]:
# Surface Thermal Radiation
# Unit is J/m^2
blr_thermal = pd.read_csv("../Data/Surface Thermal Radiation/surface_thermal_radiation_downwards_sum_BLR_New.csv")
hyd_thermal = pd.read_csv("../Data/Surface Thermal Radiation/surface_thermal_radiation_downwards_sum_HYD_New.csv")
pune_thermal = pd.read_csv("../Data/Surface Thermal Radiation/surface_thermal_radiation_downwards_sum_Pune_New.csv")

In [14]:
# Volumetric Soil Moisture
# Unitless : Volume Fraction
blr_soil = pd.read_csv("../Data/Volumetric Soli Water Layer 1/volumetric_soil_water_layer_1_BLR_New.csv")
hyd_soil = pd.read_csv("../Data/Volumetric Soli Water Layer 1/volumetric_soil_water_layer_1_HYD_New.csv")
pune_soil = pd.read_csv("../Data/Volumetric Soli Water Layer 1/volumetric_soil_water_layer_1_Pune_New.csv")

# Creating the master dataframes

In [15]:
blr_df = pd.DataFrame(columns=['Date', 'DPT', 'AP', 'WS', 'WSD', 'AT', 'Albedo', 'evaporation_from_bare_soil_sum', 'evaporation_from_vegetation_transpiration_sum', 'NDVI', 'precipitation', 'surface_net_solar_radiation_sum', 'surface_thermal_radiation_downwards_sum', 'volumetric_soil_water_layer_1','LST'])
hyd_df = pd.DataFrame(columns=['Date', 'DPT', 'AP', 'WS', 'WSD', 'AT', 'Albedo', 'evaporation_from_bare_soil_sum', 'evaporation_from_vegetation_transpiration_sum', 'NDVI', 'precipitation', 'surface_net_solar_radiation_sum', 'surface_thermal_radiation_downwards_sum', 'volumetric_soil_water_layer_1','LST'])
pune_df = pd.DataFrame(columns=['Date', 'DPT', 'AP', 'WS', 'WSD','AT', 'Albedo', 'evaporation_from_bare_soil_sum', 'evaporation_from_vegetation_transpiration_sum', 'NDVI', 'precipitation', 'surface_net_solar_radiation_sum', 'surface_thermal_radiation_downwards_sum', 'volumetric_soil_water_layer_1','LST'])

# Removing necessary columns

In [16]:
hyd_lst

,system:index,LST_Celsius,date,.geo
0,gf_Day2003_001,352.530271,2003-01-01,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,gf_Day2003_002,316.605346,2003-01-02,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,gf_Day2003_003,300.858490,2003-01-03,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,gf_Day2003_004,305.698638,2003-01-04,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,gf_Day2003_005,318.788953,2003-01-05,"{""type"":""MultiPoint"",""coordinates"":[]}"
...,...,...,...,...
6565,gf_Day2020_361,322.623439,2020-12-26,"{""type"":""MultiPoint"",""coordinates"":[]}"
6566,gf_Day2020_362,337.966272,2020-12-27,"{""type"":""MultiPoint"",""coordinates"":[]}"
6567,gf_Day2020_363,317.480700,2020-12-28,"{""type"":""MultiPoint"",""coordinates"":[]}"
6568,gf_Day2020_364,330.915973,2020-12-29,"{""type"":""MultiPoint"",""coordinates"":[]}"
6569,gf_Day2020_365,303.463004,2020-12-30,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [17]:
pune_dpt

,system:index,date,dewPointTemp,.geo
0,20030101,2003-01-01,280.250958,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,20030102,2003-01-02,283.634796,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,20030103,2003-01-03,285.756104,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,20030104,2003-01-04,285.796417,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,20030105,2003-01-05,286.216706,"{""type"":""MultiPoint"",""coordinates"":[]}"
...,...,...,...,...
6568,20201225,2020-12-25,285.246190,"{""type"":""MultiPoint"",""coordinates"":[]}"
6569,20201226,2020-12-26,286.531471,"{""type"":""MultiPoint"",""coordinates"":[]}"
6570,20201227,2020-12-27,286.969016,"{""type"":""MultiPoint"",""coordinates"":[]}"
6571,20201228,2020-12-28,286.981078,"{""type"":""MultiPoint"",""coordinates"":[]}"
6572,20201229,2020-12-29,286.665426,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [18]:
pune_ap

,system:index,date,surfacePressure,.geo
0,20030101,2003-01-01,94196.132322,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,20030102,2003-01-02,94267.543314,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,20030103,2003-01-03,94288.145684,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,20030104,2003-01-04,94300.922674,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,20030105,2003-01-05,94376.252726,"{""type"":""MultiPoint"",""coordinates"":[]}"
...,...,...,...,...
6568,20201225,2020-12-25,94105.388525,"{""type"":""MultiPoint"",""coordinates"":[]}"
6569,20201226,2020-12-26,94226.309255,"{""type"":""MultiPoint"",""coordinates"":[]}"
6570,20201227,2020-12-27,94128.769184,"{""type"":""MultiPoint"",""coordinates"":[]}"
6571,20201228,2020-12-28,94063.093892,"{""type"":""MultiPoint"",""coordinates"":[]}"
6572,20201229,2020-12-29,94027.122821,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [19]:
blr_wind

,system:index,date,u_component_of_wind_10m,v_component_of_wind_10m,.geo
0,20030101,2003-01-01,-0.327114,0.513567,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,20030102,2003-01-02,-2.819963,1.043748,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,20030103,2003-01-03,-2.829072,0.494821,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,20030104,2003-01-04,-2.668422,0.231232,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,20030105,2003-01-05,-3.091901,0.284496,"{""type"":""MultiPoint"",""coordinates"":[]}"
...,...,...,...,...,...
6569,20201226,2020-12-26,-2.219871,-0.649711,"{""type"":""MultiPoint"",""coordinates"":[]}"
6570,20201227,2020-12-27,-2.150850,-0.694880,"{""type"":""MultiPoint"",""coordinates"":[]}"
6571,20201228,2020-12-28,-1.928350,-0.544585,"{""type"":""MultiPoint"",""coordinates"":[]}"
6572,20201229,2020-12-29,-2.369977,0.113602,"{""type"":""MultiPoint"",""coordinates"":[]}"
6573,20201230,2020-12-30,-3.265377,-0.210665,"{""type"":""MultiPoint"",""coordinates"":[]}"

### Looking at the data, we see that that system:index, .geo are unnecessary for our analysis, hence we shall drop them.

In [20]:
def dropColumns(df):
    return df.drop(columns=['system:index', '.geo'], errors='ignore')

In [21]:
datasets = [blr_lst, hyd_lst, pune_lst,
            blr_dpt, hyd_dpt, pune_dpt,
            blr_ap, hyd_ap, pune_ap,
            blr_wind, hyd_wind, pune_wind, blr_at, hyd_at, pune_at, 
            blr_albedo, hyd_albedo, pune_albedo, 
            blr_evap_soil, hyd_evap_soil, pune_evap_soil,
            blr_evap_veg, hyd_evap_veg, pune_evap_veg,
            blr_ndvi, hyd_ndvi, pune_ndvi,
            blr_precip, hyd_precip, pune_precip,
            blr_solar, hyd_solar, pune_solar,
            blr_thermal, hyd_thermal, pune_thermal,
            blr_soil, hyd_soil, pune_soil]

In [22]:
datasets = [dropColumns(df) for df in datasets]

In [23]:
(   blr_lst, hyd_lst, pune_lst,
    blr_dpt, hyd_dpt, pune_dpt,
    blr_ap, hyd_ap, pune_ap,
    blr_wind, hyd_wind, pune_wind, blr_at, hyd_at, pune_at, 
    blr_albedo, hyd_albedo, pune_albedo, 
    blr_evap_soil, hyd_evap_soil, pune_evap_soil,
    blr_evap_veg, hyd_evap_veg, pune_evap_veg,
    blr_ndvi, hyd_ndvi, pune_ndvi,
    blr_precip, hyd_precip, pune_precip,
    blr_solar, hyd_solar, pune_solar,
    blr_thermal, hyd_thermal, pune_thermal,
    blr_soil, hyd_soil, pune_soil) = datasets

### Dropping Duplicates

In [24]:
def clean_dates(df):
    df['date'] = pd.to_datetime(df['date'], errors='coerce').dt.date
    df = df.dropna(subset=['date'])
    df = df.drop_duplicates(subset='date')
    return df

In [25]:
datasets = [clean_dates(df) for df in datasets]

In [26]:
(   blr_lst, hyd_lst, pune_lst,
    blr_dpt, hyd_dpt, pune_dpt,
    blr_ap, hyd_ap, pune_ap,
    blr_wind, hyd_wind, pune_wind, blr_at, hyd_at, pune_at, 
    blr_albedo, hyd_albedo, pune_albedo, 
    blr_evap_soil, hyd_evap_soil, pune_evap_soil,
    blr_evap_veg, hyd_evap_veg, pune_evap_veg,
    blr_ndvi, hyd_ndvi, pune_ndvi,
    blr_precip, hyd_precip, pune_precip,
    blr_solar, hyd_solar, pune_solar,
    blr_thermal, hyd_thermal, pune_thermal,
    blr_soil, hyd_soil, pune_soil) = datasets

### We can see that there is a mismatch between the number of entries across different datasets. For that I shall take all the common entries based on date in the tables

In [27]:
# Extract date sets
lst_dates = set(blr_lst['date']) & set(hyd_lst['date']) & set(pune_lst['date'])
dpt_dates = set(blr_dpt['date']) & set(hyd_dpt['date']) & set(pune_dpt['date'])
ap_dates = set(blr_ap['date']) & set(hyd_ap['date']) & set(pune_ap['date'])
wind_dates = set(blr_wind['date']) & set(hyd_wind['date']) & set(pune_wind['date'])
at_dates = set(blr_at['date']) & set(hyd_at['date']) & set(pune_at['date'])
albedo_dates = set(blr_albedo['date']) & set(hyd_albedo['date']) & set(pune_albedo['date'])
evap_soil_dates = set(blr_evap_soil['date']) & set(hyd_evap_soil['date']) & set(pune_evap_soil['date'])
evap_veg_dates = set(blr_evap_veg['date']) & set(hyd_evap_veg['date']) & set(pune_evap_veg['date'])
ndvi_dates = set(blr_ndvi['date']) & set(hyd_ndvi['date']) & set(pune_ndvi['date'])
precip_dates = set(blr_precip['date']) & set(hyd_precip['date']) & set(pune_precip['date'])
solar_dates = set(blr_solar['date']) & set(hyd_solar['date']) & set(pune_solar['date'])
thermal_dates = set(blr_thermal['date']) & set(hyd_thermal['date']) & set(pune_thermal['date'])
soil_dates = set(blr_soil['date']) & set(hyd_soil['date']) & set(pune_soil['date'])

In [28]:
# Final common dates
common_dates = lst_dates & dpt_dates & ap_dates & wind_dates & at_dates
common_dates = sorted(list(common_dates))  # Ensure chronological order

In [29]:
def filter_dates(df, common_dates):
    return df[df['date'].isin(common_dates)].sort_values('date').reset_index(drop=True)

In [30]:
datasets = [filter_dates(df, common_dates) for df in datasets]

In [31]:
(   blr_lst, hyd_lst, pune_lst,
    blr_dpt, hyd_dpt, pune_dpt,
    blr_ap, hyd_ap, pune_ap,
    blr_wind, hyd_wind, pune_wind, blr_at, hyd_at, pune_at, 
    blr_albedo, hyd_albedo, pune_albedo, 
    blr_evap_soil, hyd_evap_soil, pune_evap_soil,
    blr_evap_veg, hyd_evap_veg, pune_evap_veg,
    blr_ndvi, hyd_ndvi, pune_ndvi,
    blr_precip, hyd_precip, pune_precip,
    blr_solar, hyd_solar, pune_solar,
    blr_thermal, hyd_thermal, pune_thermal,
    blr_soil, hyd_soil, pune_soil) = datasets

In [32]:
lst_tables = [blr_lst, hyd_lst, pune_lst]
dpt_tables = [blr_dpt, hyd_dpt, pune_dpt]
ap_tables = [blr_ap, hyd_ap, pune_ap]
wind_tables = [blr_wind, hyd_wind, pune_wind]
at_tables = [blr_at, hyd_at, pune_at]
albedo_tables = [blr_albedo, hyd_albedo, pune_albedo]
evap_soil_tables = [blr_evap_soil, hyd_evap_soil, pune_evap_soil]
evap_veg_tables = [blr_evap_veg, hyd_evap_veg, pune_evap_veg]
ndvi_tables = [blr_ndvi, hyd_ndvi, pune_ndvi]
precip_tables = [blr_precip, hyd_precip, pune_precip]
solar_tables = [blr_solar, hyd_solar, pune_solar]
thermal_tables = [blr_thermal, hyd_thermal, pune_thermal]
soil_tables = [blr_soil, hyd_soil, pune_soil]

In [33]:
from typing import List

In [34]:
def print_shape(df_list : list[pd.DataFrame]) -> None:
    for df in df_list:
        print(df.shape)

In [35]:
print_shape(lst_tables)
print_shape(dpt_tables)
print_shape(ap_tables)
print_shape(wind_tables)
print_shape(at_tables)
print_shape(albedo_tables)
print_shape(evap_soil_tables)
print_shape(evap_veg_tables)
print_shape(ndvi_tables)
print_shape(precip_tables)
print_shape(solar_tables)
print_shape(thermal_tables)
print_shape(soil_tables)

(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 3)
(6558, 3)
(6558, 3)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6540, 2)
(6540, 2)
(6540, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)
(6558, 2)

### Calculating the magnitude of wind speed and direction

In [36]:
def calculateWindSpeed(df : pd.DataFrame) -> pd.DataFrame:
    """
    Calculate wind speed from u and v components.
    """
    df['WS'] = np.sqrt(df['u_component_of_wind_10m']**2 + df['v_component_of_wind_10m']**2)
    return df

In [37]:
def calculateWindDirection(df : pd.DataFrame) -> pd.DataFrame:
    """
    Calculate wind direction from u and v components.
    """
    df['WSD'] = np.arctan2(df['u_component_of_wind_10m'], df['v_component_of_wind_10m']) * 180 / np.pi
    df['WSD'] = (df['WSD'] + 360) % 360  # Normalize to [0, 360)
    return df

In [38]:
blr_wind = calculateWindSpeed(blr_wind)
pune_wind = calculateWindSpeed(pune_wind)
hyd_wind = calculateWindSpeed(hyd_wind)

In [39]:
blr_wind = calculateWindDirection(blr_wind)
pune_wind = calculateWindDirection(pune_wind)
hyd_wind = calculateWindDirection(hyd_wind)

In [40]:
blr_wind

,date,u_component_of_wind_10m,v_component_of_wind_10m,WS,WSD
0,2003-01-01,-0.327114,0.513567,0.608896,327.505071
1,2003-01-02,-2.819963,1.043748,3.006925,290.310937
2,2003-01-03,-2.829072,0.494821,2.872020,279.921010
3,2003-01-04,-2.668422,0.231232,2.678422,274.952584
4,2003-01-05,-3.091901,0.284496,3.104962,275.257170
...,...,...,...,...,...
6553,2020-12-25,-2.128752,-0.319760,2.152634,261.457477
6554,2020-12-26,-2.219871,-0.649711,2.312996,253.686322
6555,2020-12-27,-2.150850,-0.694880,2.260313,252.095788
6556,2020-12-28,-1.928350,-0.544585,2.003774,254.229795
6557,2020-12-29,-2.369977,0.113602,2.372698,272.744304

In [41]:
hyd_wind

,date,u_component_of_wind_10m,v_component_of_wind_10m,WS,WSD
0,2003-01-01,-2.039009,-1.773130,2.702138,228.989644
1,2003-01-02,-2.833919,0.902780,2.974241,287.669929
2,2003-01-03,-2.358774,1.878723,3.015529,308.536731
3,2003-01-04,-1.624962,0.915442,1.865083,299.395258
4,2003-01-05,-2.278999,-0.198965,2.287668,265.010524
...,...,...,...,...,...
6553,2020-12-25,-1.866285,0.760561,2.015309,292.172202
6554,2020-12-26,-1.682583,0.428816,1.736367,284.297801
6555,2020-12-27,-1.665262,0.550966,1.754041,288.307250
6556,2020-12-28,-1.744834,1.003069,2.012608,299.893708
6557,2020-12-29,-2.307411,1.075839,2.545894,294.997468

In [42]:
pune_wind

,date,u_component_of_wind_10m,v_component_of_wind_10m,WS,WSD
0,2003-01-01,-1.915287,-0.264482,1.933461,262.137755
1,2003-01-02,-1.231768,0.738244,1.436056,300.935828
2,2003-01-03,-1.283637,0.749544,1.486452,300.281597
3,2003-01-04,-1.456962,0.259006,1.479805,280.080236
4,2003-01-05,-2.159280,-0.042317,2.159695,268.877282
...,...,...,...,...,...
6553,2020-12-25,-2.193491,0.341258,2.219879,278.843058
6554,2020-12-26,-1.308702,0.164616,1.319014,277.169354
6555,2020-12-27,0.220888,-0.542025,0.585305,157.827979
6556,2020-12-28,-0.065363,-0.340671,0.346885,190.861072
6557,2020-12-29,-0.610590,0.200751,0.642745,288.199968

In [43]:
blr_lst

      LST_Celsius        date
0      309.395285  2003-01-01
1      311.791133  2003-01-02
2      330.457050  2003-01-03
3      382.669334  2003-01-04
4      331.853939  2003-01-05
...           ...         ...
6553   321.187581  2020-12-25
6554   320.680087  2020-12-26
6555   345.393270  2020-12-27
6556   313.103988  2020-12-28
6557   329.456816  2020-12-29

[6558 rows x 2 columns]

### Combining all the information to a single dataframe

In [44]:
blr_df['Date'] = blr_lst['date']
blr_df['LST'] = blr_lst['LST_Celsius']
blr_df['DPT'] = blr_dpt['dewPointTemp']
blr_df['AP'] = blr_ap['surfacePressure']
blr_df['WS'] = blr_wind['WS']
blr_df['WSD'] = blr_wind['WSD']
blr_df['Albedo'] = blr_albedo['Albedo_BSA_shortwave']
blr_df['evaporation_from_bare_soil_sum'] = blr_evap_soil['evaporation_from_bare_soil_sum']
blr_df['evaporation_from_vegetation_transpiration_sum'] = blr_evap_veg['evaporation_from_vegetation_transpiration_sum']
blr_df['NDVI'] = blr_ndvi['NDVI']
blr_df['precipitation'] = blr_precip['precipitation']
blr_df['surface_net_solar_radiation_sum'] = blr_solar['surface_net_solar_radiation_sum']
blr_df['surface_thermal_radiation_downwards_sum'] = blr_thermal['surface_thermal_radiation_downwards_sum']
blr_df['volumetric_soil_water_layer_1'] = blr_soil['volumetric_soil_water_layer_1']
blr_df['AT'] = blr_at['airTemp']

In [45]:
hyd_df['Date'] = hyd_lst['date']
hyd_df['LST'] = hyd_lst['LST_Celsius']
hyd_df['DPT'] = hyd_dpt['dewPointTemp']
hyd_df['AP'] = hyd_ap['surfacePressure']
hyd_df['WS'] = hyd_wind['WS']
hyd_df['WSD'] = hyd_wind['WSD']
hyd_df['Albedo'] = hyd_albedo['Albedo_BSA_shortwave']
hyd_df['evaporation_from_bare_soil_sum'] = hyd_evap_soil['evaporation_from_bare_soil_sum']
hyd_df['evaporation_from_vegetation_transpiration_sum'] = hyd_evap_veg['evaporation_from_vegetation_transpiration_sum']
hyd_df['NDVI'] = hyd_ndvi['NDVI']
hyd_df['precipitation'] = hyd_precip['precipitation']
hyd_df['surface_net_solar_radiation_sum'] = hyd_solar['surface_net_solar_radiation_sum']
hyd_df['surface_thermal_radiation_downwards_sum'] = hyd_thermal['surface_thermal_radiation_downwards_sum']
hyd_df['volumetric_soil_water_layer_1'] = hyd_soil['volumetric_soil_water_layer_1']
hyd_df['AT'] = hyd_at['airTemp']

In [46]:
pune_df['Date'] = pune_lst['date']
pune_df['LST'] = pune_lst['LST_Celsius']
pune_df['DPT'] = pune_dpt['dewPointTemp']
pune_df['AP'] = pune_ap['surfacePressure']
pune_df['WS'] = pune_wind['WS']
pune_df['WSD'] = pune_wind['WSD']
pune_df['Albedo'] = pune_albedo['Albedo_BSA_shortwave']
pune_df['evaporation_from_bare_soil_sum'] = pune_evap_soil['evaporation_from_bare_soil_sum']
pune_df['evaporation_from_vegetation_transpiration_sum'] = pune_evap_veg['evaporation_from_vegetation_transpiration_sum']
pune_df['NDVI'] = pune_ndvi['NDVI']
pune_df['precipitation'] = pune_precip['precipitation']
pune_df['surface_net_solar_radiation_sum'] = pune_solar['surface_net_solar_radiation_sum']
pune_df['surface_thermal_radiation_downwards_sum'] = pune_thermal['surface_thermal_radiation_downwards_sum']
pune_df['volumetric_soil_water_layer_1'] = pune_soil['volumetric_soil_water_layer_1']
pune_df['AT'] = pune_at['airTemp']

In [47]:
blr_df.isna().sum()

Date                                               0
DPT                                                0
AP                                                 0
WS                                                 0
WSD                                                0
AT                                                 0
Albedo                                           183
evaporation_from_bare_soil_sum                     0
evaporation_from_vegetation_transpiration_sum      0
NDVI                                             453
precipitation                                      0
surface_net_solar_radiation_sum                    0
surface_thermal_radiation_downwards_sum            0
volumetric_soil_water_layer_1                      0
LST                                                0
dtype: int64

In [48]:
hyd_df.isna().sum()

Date                                               0
DPT                                                0
AP                                                 0
WS                                                 0
WSD                                                0
AT                                                 0
Albedo                                           617
evaporation_from_bare_soil_sum                     0
evaporation_from_vegetation_transpiration_sum      0
NDVI                                             438
precipitation                                      0
surface_net_solar_radiation_sum                    0
surface_thermal_radiation_downwards_sum            0
volumetric_soil_water_layer_1                      0
LST                                                0
dtype: int64

In [49]:
pune_df.isna().sum()

Date                                              0
DPT                                               0
AP                                                0
WS                                                0
WSD                                               0
AT                                                0
Albedo                                           44
evaporation_from_bare_soil_sum                    0
evaporation_from_vegetation_transpiration_sum     0
NDVI                                             32
precipitation                                     0
surface_net_solar_radiation_sum                   0
surface_thermal_radiation_downwards_sum           0
volumetric_soil_water_layer_1                     0
LST                                               0
dtype: int64

## Converting the units to Celsisus, metres/second, pascal to hPa

In [50]:
def lstCorrect(df : pd.DataFrame) -> pd.DataFrame:
    """
    Corrects the LST values based on the RH values.
    """
    df['LST'] = df['LST'] * 0.1
    return df

In [51]:
def toCelsius(df : pd.DataFrame, col: str) -> pd.DataFrame:
    """
    Converts Kelvin to Celsius.
    """
    df[col] = df[col] - 273.15
    return df

In [52]:
def paTohPa(df : pd.DataFrame, col: str) -> pd.DataFrame:
    """
    Converts Pa to hPa.
    """
    df[col] = df[col] / 100
    return df

In [53]:
blr_df = lstCorrect(blr_df)
hyd_df = lstCorrect(hyd_df)
pune_df = lstCorrect(pune_df)

In [54]:
blr_df = toCelsius(blr_df, 'DPT')
hyd_df = toCelsius(hyd_df, 'DPT')
pune_df = toCelsius(pune_df, 'DPT')

In [55]:
blr_df = paTohPa(blr_df, 'AP')
pune_df = paTohPa(pune_df, 'AP')
hyd_df = paTohPa(hyd_df, 'AP')

In [56]:
blr_df

,Date,DPT,AP,WS,WSD,AT,Albedo,evaporation_from_bare_soil_sum,evaporation_from_vegetation_transpiration_sum,NDVI,precipitation,surface_net_solar_radiation_sum,surface_thermal_radiation_downwards_sum,volumetric_soil_water_layer_1,LST
0,2003-01-01,12.498648,916.589625,0.608896,327.505071,294.583644,0.164460,-0.000866,-0.000029,0.265743,0.000000,1.427781e+07,31100000.0,0.192649,30.939528
1,2003-01-02,12.825784,918.004624,3.006925,290.310937,294.396121,0.164931,-0.000744,-0.000054,0.321507,0.006589,1.279035e+07,31500000.0,0.192116,31.179113
2,2003-01-03,12.970981,918.453619,2.872020,279.921010,293.651644,0.165501,-0.000771,-0.000051,0.402250,0.000000,1.492127e+07,30700000.0,0.191724,33.045705
3,2003-01-04,12.445614,917.966755,2.678422,274.952584,294.383796,0.165904,-0.000971,-0.000048,0.370532,0.000000,1.747538e+07,29400000.0,0.191393,38.266933
4,2003-01-05,14.071074,918.579933,3.104962,275.257170,294.637442,0.165906,-0.000843,-0.000050,0.407205,0.000000,1.584263e+07,30200000.0,0.190960,33.185394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6553,2020-12-25,13.500707,916.151180,2.152634,261.457477,292.513759,0.140036,-0.002592,-0.000046,NaN,0.000000,1.671576e+07,29200000.0,0.297770,32.118758
6554,2020-12-26,12.901577,917.194971,2.312996,253.686322,292.035179,0.140023,-0.002544,-0.000056,NaN,0.000000,1.764899e+07,28000000.0,0.289527,32.068009
6555,2020-12-27,12.950693,916.302854,2.260313,252.095788,292.771807,0.139925,-0.002661,-0.000051,NaN,0.000000,1.757099e+07,28200000.0,0.281540,34.539327
6556,2020-12-28,10.830827,916.237697,2.003774,254.229795,292.428852,0.139896,-0.002655,-0.000055,NaN,0.000000,1.724660e+07,28200000.0,0.273806,31.310399
6557,2020-12-29,16.207934,915.751192,2.372698,272.744304,294.122393,0.139868,-0.001962,-0.000026,NaN,0.000000,1.392139e+07,32900000.0,0.268557,32.945682

In [57]:
hyd_df

,Date,DPT,AP,WS,WSD,AT,Albedo,evaporation_from_bare_soil_sum,evaporation_from_vegetation_transpiration_sum,NDVI,precipitation,surface_net_solar_radiation_sum,surface_thermal_radiation_downwards_sum,volumetric_soil_water_layer_1,LST
0,2003-01-01,9.801921,952.321702,2.702138,228.989644,294.587935,0.150061,-0.000407,-0.000179,0.230621,0.0,1.548250e+07,28900000.0,0.119923,35.253027
1,2003-01-02,12.894156,953.896739,2.974241,287.669929,295.364687,0.151337,-0.000302,-0.000127,0.197456,0.0,1.177422e+07,32300000.0,0.120030,31.660535
2,2003-01-03,16.945643,954.471306,3.015529,308.536731,294.436472,0.151539,-0.000128,-0.000058,0.019037,0.0,9.142362e+06,33300000.0,0.126387,30.085849
3,2003-01-04,17.761199,954.172469,1.865083,299.395258,293.495316,0.151312,-0.000044,-0.000026,0.079633,0.0,4.418173e+06,33600000.0,0.155643,30.569864
4,2003-01-05,14.281283,954.395644,2.287668,265.010524,296.410658,0.151222,-0.000545,-0.000079,0.194655,0.0,1.449708e+07,31500000.0,0.155939,31.878895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6553,2020-12-25,13.330685,951.670802,2.015309,292.172202,293.417897,0.132338,-0.001512,-0.000082,NaN,0.0,1.558327e+07,28400000.0,0.144402,30.396700
6554,2020-12-26,14.027632,952.521458,1.736367,284.297801,293.992337,0.132305,-0.001512,-0.000066,NaN,0.0,1.571960e+07,28400000.0,0.143072,32.262344
6555,2020-12-27,13.223768,951.342613,1.754041,288.307250,294.178115,0.132271,-0.001620,-0.000077,NaN,0.0,1.594387e+07,28100000.0,0.141706,33.796627
6556,2020-12-28,12.504071,951.101661,2.012608,299.893708,294.514357,0.132201,-0.001720,-0.000089,NaN,0.0,1.591720e+07,28400000.0,0.140171,31.748070
6557,2020-12-29,12.890767,951.123203,2.545894,294.997468,294.206161,0.132131,-0.001637,-0.000116,NaN,0.0,1.594922e+07,28300000.0,0.138732,33.091597

In [58]:
pune_df

,Date,DPT,AP,WS,WSD,AT,Albedo,evaporation_from_bare_soil_sum,evaporation_from_vegetation_transpiration_sum,NDVI,precipitation,surface_net_solar_radiation_sum,surface_thermal_radiation_downwards_sum,volumetric_soil_water_layer_1,LST
0,2003-01-01,7.100958,941.961323,1.933461,262.137755,291.684654,0.136310,-0.000517,-0.000160,0.457425,0.000000,1.617383e+07,26800000.0,0.148610,34.246204
1,2003-01-02,10.484796,942.675433,1.436056,300.935828,294.195680,0.136204,-0.000475,-0.000130,0.359140,0.000000,1.418103e+07,30800000.0,0.148434,35.734294
2,2003-01-03,12.606104,942.881457,1.486452,300.281597,295.828579,0.136274,-0.000444,-0.000083,0.333687,0.000000,1.168451e+07,32600000.0,0.148452,32.590960
3,2003-01-04,12.646417,943.009227,1.479805,280.080236,295.986278,0.136218,-0.000461,-0.000058,0.361981,0.000000,1.190128e+07,32100000.0,0.148349,35.435619
4,2003-01-05,13.066706,943.762527,2.159695,268.877282,296.071805,0.135858,-0.000515,-0.000077,0.361361,0.000000,1.382363e+07,31200000.0,0.148208,34.235347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6553,2020-12-25,12.096190,941.053885,2.219879,278.843058,294.637357,0.127867,-0.001178,-0.000121,NaN,0.125304,1.532697e+07,29600000.0,0.171530,33.209944
6554,2020-12-26,13.381471,942.263093,1.319014,277.169354,295.234928,0.127843,-0.001168,-0.000078,NaN,0.000000,1.530680e+07,29900000.0,0.168792,31.352555
6555,2020-12-27,13.819016,941.287692,0.585305,157.827979,295.475096,0.127817,-0.001195,-0.000068,NaN,0.000000,1.524516e+07,30000000.0,0.166471,33.862652
6556,2020-12-28,13.831078,940.630939,0.346885,190.861072,295.019423,0.127371,-0.001151,-0.000072,NaN,0.000000,1.555207e+07,29500000.0,0.164420,32.318171
6557,2020-12-29,13.515426,940.271228,0.642745,288.199968,294.923524,0.127055,-0.001128,-0.000086,NaN,0.000000,1.557578e+07,29500000.0,0.162695,34.509701

### Exporting the prepared data

In [59]:
os.makedirs('../Data/Processed', exist_ok=True)

In [60]:
blr_df.to_csv('../Data/Processed/blr_df_enhanced.csv', index=False)
hyd_df.to_csv('../Data/Processed/hyd_df_enhanced.csv', index=False)
pune_df.to_csv('../Data/Processed/pune_df_enhanced.csv', index=False)